### PR TITLE
fix --vmtrace for vmTests

### PR DESCRIPTION
**Pull request by winsvega**
connects to https://github.com/ethereum/webthree-umbrella/issues/704
connects to https://github.com/ethereum/webthree-umbrella/issues/703

### CODE REVIEW

**Comment by chfast** [comment]
This looks very nice, but probably should be sent to https://github.com/ethereum/cpp-ethereum.

**Comment by winsvega** [comment]
it would be one hell of a PR's 
https://github.com/ethereum/cpp-ethereum/compare/develop...winsvega:fixvmtrace

what is the lateset branch ?

**Comment by bobsummerwill** [comment]
Yep - it needs rebuilding against `develop` in https://github.com/ethereum/cpp-ethereum.

**Comment by gcolvin** [comment]
Total accident that is landed on your branch Bob -- I can't even imagine how I got here.

**Pull request closed without merging**
