### PR TITLE
Simplify CMake files, so they are mainly using built-in functionality

### PR DESCRIPTION
**Pull request by bobsummerwill**

### CODE REVIEW

**Comment by chfast** [comment]
This is great man! I always wanted to do it!

**Comment by bobsummerwill** [comment]
Thanks, @chfast.

It took less than a day, and makes things so much better.    I think there is likely plenty more cleanup which can happen from here, but this PR has fixed the bulk of the `eth_use()` weirdness and replaced all the implicit/indirect dependencies with just plain explicit dependencies exactly where things are being used.

Just need to work through pthreads and Windows-specific conditionals.

**Comment by bobsummerwill** [comment]
So these changes are in a PR-of-my-branch, because they cannot be committed until AFTER all the history-preserving-changes have been done.

I am just iterating on the content here, and then will make a new PR against ethereum/cpp-ethereum after the big merge.

**Comment by bobsummerwill** [comment]
So FYI ... this looks like it's just about "done", @chfast.

Building cleanly on Windows now as well as macOS.    Maybe 1-2 more iterations needed on Ubuntu Trusty.

If you want to review the diffs, please do!   Thank would be very helpful.

**Comment by bobsummerwill** [comment]
Hey @chfast,

So I think these changes are "done" now.    I removed the last of the "base" CMake support yesterday (adding pthreads directly where needed).

Here is what the diagram looks like now:

image

So yeah - please do review, and I will commit it right after the git-migration and before the v1.3.1 release.

**Comment by bobsummerwill** [comment]
Superceded by PR against ethereum/cpp-ethereum.

**Pull request closed without merging**
